name = "pdf-gen"
compatibility_date = "2023-12-01"

[build]
command = "npm run build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "out"

pages_build_output_dir = "out" 