name = "pdf-gen"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = "out"

[site]
bucket = "out"

[build.upload]
format = "service-worker" 